#!/usr/bin/python
import os, sys
import hashlib

""" 
Similarities checker
This program searches through subdirectories and returns lists of all files with same sha1 separated by a semicolon ";".
"""

if len(sys.argv) == 1:
    print("No directory name provided...\nUsage: shacheck Path/To/Directory")
    sys.exit()

relative_directory = sys.argv[1]

dir_data = [] #Will contain a list of all file paths

def hash_file(filename):
   """"This function returns the SHA-1 hash
   of the file passed into it"""

   # make a hash object
   h = hashlib.sha1()

   # open file for reading in binary mode
   with open(filename,'rb') as file:

       # loop till the end of the file
       chunk = 0
       while chunk != b'':
          # read only 1024 bytes at a time
          chunk = file.read(1024)
          h.update(chunk)

   # return the hex representation of digest
   return h.hexdigest()


def iterate_dirs(root="null",data=dir_data):
    """Appends a dictionary with a key value pair of filename and filehash from all the files in the directory and subdirectories."""
    if root == "null":
        if relative_directory[0] == "/":
            root = relative_directory + "/"
        else:
            root = "/home/" + os.getlogin() + "/" +  relative_directory +  "/"
    for i in os.listdir(root):
        path = root + i
        try:
            if os.path.isdir(path):
                raise IsADirectoryError
            else:
                #print("Path is "+ path)
                data.append(path)
        except IsADirectoryError:
            directory = root + i + "/"
            iterate_dirs(root=directory, data=data)
            #print("The following is a directory: " + root + i)


def hash_dict(paths):
    """"Returns a dictionary with paths provided as keys and their hashes as values for the key."""
    hash_table = {}
    for i in paths:
        file_hash = hash_file(i)
        hash_table[i] = file_hash
    print(hash_table)
    return hash_table

def compare_sha(data):
    """Returns a list of all items in a dictionary with a same key."""
    checked = []
    similar_files = []
    for k in data:
        if k in checked:
            pass # Ignore if the item has been already checked
        else:
            paths = list()
            paths.append(k)
            for kk in data :
                if k == kk:
                    pass
                elif data[kk] == data[k]:
                    paths.append(kk)
                    checked.append(kk)
            if len(paths) > 1: similar_files.append(paths)
    return similar_files


def return_common_lists(l):
    """Returns all list items in a list after separating them with a semicolon ';'. """
    for i in l:
        print("")
        print(*i, sep=':')


iterate_dirs(data=dir_data)
compare_sha(hash_dict(dir_data))


if __name__ == "__maoin__":
    pass
    #print("Populating directories list...")
    #iterate_hash()
    #print("Comparing files for similarities...")
    #files = compare_sha()
    #return_common_lists(files)

